services:
  morock-backend-server:
    build: .
    ports:
      - 8080:8080

  postgre-db-server:
    build:
      context: .
    container_name: morock-backend-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
    depends_on: []
    restart: always

networks:
  default:
    driver: bridge